kind: Deployment
apiVersion: apps/v1
metadata:
  name: stable
spec:
  replicas: 5
  selector:
    matchLabels:
      app: stable
  strategy:
    rollingUpdate:
      maxSurge: 75%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: stable
    spec:
      containers:
        - name: stable
          image: sreemaish/marvelapp:5.0
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: stable
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: stable
